version: "3.6"
services:
  ensemble:
    container_name: ensemble
    image: ensemble-dxc:latest
    ports:
      - 1972:1972
      - 57772:57772
    volumes:
      - ./local-storage/ensemble:/home/repos:z
      - ./import/ensemble:/home/import:z
      - ./export/ensemble:/home/export:z
      - ./database/ensemble:/opt/database:z
  # iris:
  #   container_name: ensemble
  #   image: iris-dxc:latest
  #   ports:
  #     - 11972:1972
  #     - 57773:57772
  #   volumes:
  #     - ./local-storage/iris:/home/repos:z
  #     - ./import/iris:/home/import:z
  #     - ./export/iris:/home/export:z
  #     - ./database/iris:/database:z