version: "3.6"

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  my-iris:
    container_name: iris
    hostname: iris.local.com
    image: containers.intersystems.com/intersystems/irishealth:2022.1.0.209.0
    environment:
      ISC_DATA_DIRECTORY: /opt/external/dur
    ports:
      - 1973:1972
      - 57773:52773
    command: --check-caps false --key /home/key/iris.key
    volumes:
      - repolocation:/opt/repos
      - ../../TiCSData:/opt/TiCSData
      - ./import/iris:/home/import:z
      - ./export/iris:/home/export:z
      - ./iris/iris.key:/home/key/iris.key:z
      - ./database/iris:/opt/database
      - ./irisdata:/opt/external:z
    networks:
      web:
        ipv4_address: 172.20.0.3
      internal:
    restart: always

volumes:
  repolocation:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../