version: "3.6"
services:
  ensemble:
    container_name: ensemble
    image: ensemble-dxc:latest
    ports:
      - 1972:1972
      - 57772:57772
    volumes:
      - ./local-storage/ensemble:/home/repos:z
      - ./import/ensemble:/home/import:z
      - ./export/ensemble:/home/export:z
      - ./database/ensemble:/opt/database:z
  my-iris:
    container_name: iris
    image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
    ports:
      - 1973:1972
      - 57773:52773
    command: --check-caps false --key /home/key/iris.key
    volumes:
      - ./local-storage/iris:/home/repos:z
      - ./import/iris:/home/import:z
      - ./export/iris:/home/export:z
      - ./iris/iris.key:/home/key/iris.key:z
      - ./database/iris:/opt/database:z
      - irisdata:/usr/irissys/mgr/

volumes:
  irisdata: